# docker build --no-cache -f Dockerfile.amazon -t pdo_duckdb_arch .
# docker run --rm -it pdo_duckdb_arch

FROM archlinux:latest

ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"

RUN <<EOF
    set -euxo pipefail
    pacman -Syu --noconfirm
    pacman -S php unzip --noconfirm
    curl -fsSL -o /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar
    echo extension=iconv >> /etc/php/php.ini
    php /tmp/pie install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
EOF
