# docker build --no-cache -f Dockerfile.swoole -t pdo_duckdb_swoole .
# docker run --rm -it pdo_duckdb_swoole

FROM ubuntu:24.04

ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"

SHELL ["/bin/bash", "-c"]

COPY ./ /pdo-duckdb

RUN <<EOF
    set -euxo pipefail
    apt-get -y update
    apt-get -y --no-install-recommends install apt-transport-https curl ca-certificates unzip
    echo "deb https://packages.sury.org/php/ noble main" >/etc/apt/sources.list.d/ondrej-php.list
    curl -s https://packages.sury.org/php/apt.gpg >/etc/apt/trusted.gpg.d/php.gpg
    apt-get -y update
    apt-get -y --no-install-recommends install php8.5-cli php8.5-swoole
    curl -fsSL -o /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar
    php /tmp/pie install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
    php /pdo-duckdb/test_swoole.php
    apt-get upgrade -y && apt-get clean
    rm -rf /tmp/* /var/lib/apt/lists/* /var/cache/apt/archives/*
EOF
