# docker build --no-cache -f Dockerfile.swoole_zts -t pdo_duckdb_swoole_zts .
# docker run --rm -it pdo_duckdb_swoole_zts

FROM ubuntu:24.04

ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"

SHELL ["/bin/bash", "-c"]

COPY ./ /pdo-duckdb

RUN <<EOF
    set -euxo pipefail
    apt-get -y update
    apt-get -y --no-install-recommends install apt-transport-https curl ca-certificates unzip
    curl -s https://pkg.henderkes.com/api/packages/85/debian/repository.key -o /etc/apt/keyrings/static-php85.asc
    echo "deb [signed-by=/etc/apt/keyrings/static-php85.asc] https://pkg.henderkes.com/api/packages/85/debian php-zts main" | \
        tee -a /etc/apt/sources.list.d/static-php85.list
    apt-get update
    apt-get install -y --no-install-recommends php-zts-cli php-zts-pdo pie-zts
    # pie-zts crashes when swoole is installed
    pie-zts install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    apt-get install -y --no-install-recommends php-zts-swoole
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
    php /pdo-duckdb/test_swoole.php
    apt-get upgrade -y && apt-get clean
    rm -rf /tmp/* /var/lib/apt/lists/* /var/cache/apt/archives/*
EOF
