# docker build --pull --no-cache -f Dockerfile.php_alpine -t pdo_duckdb_php_alpine .
# docker run --rm -it pdo_duckdb_php_alpine

# php 8.2
FROM php:8.2-cli-alpine AS php82
ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"
RUN <<EOF
    set -euxo pipefail
    apk update
    apk add --no-cache tzdata libstdc++
    ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
    curl -fsSL -o /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar
    php /tmp/pie install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
EOF

# php 8.3
FROM php:8.3-cli-alpine AS php83
COPY --from=php82 /etc/issue /etc/issue
ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"
RUN <<EOF
    set -euxo pipefail
    apk update
    apk add --no-cache tzdata libstdc++
    ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
    curl -fsSL -o /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar
    php /tmp/pie install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
EOF

# php 8.4
FROM php:8.4-cli-alpine AS php84
COPY --from=php83 /etc/issue /etc/issue
ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"
RUN <<EOF
    set -euxo pipefail
    apk update
    apk add --no-cache tzdata libstdc++
    ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
    curl -fsSL -o /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar
    php /tmp/pie install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
EOF

# php 8.5
FROM php:8.5-cli-alpine AS php85
COPY --from=php84 /etc/issue /etc/issue
ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"
RUN <<EOF
    set -euxo pipefail
    apk update
    apk add --no-cache tzdata libstdc++
    ln -s /usr/share/zoneinfo/Europe/Brussels /etc/localtime
    curl -fsSL -o /tmp/pie https://github.com/php/pie/releases/latest/download/pie.phar
    php /tmp/pie install --no-build-tools-check -v thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
EOF
