# docker build --no-cache -f Dockerfile.fedora -t pdo_duckdb_fedora .
# docker run --rm -it pdo_duckdb_fedora

FROM fedora:latest

ENV TERM="xterm-256color"
ENV LC_ALL="C.UTF-8"

RUN <<EOF
    set -euxo pipefail
    dnf -y install unzip php-cli php-pdo pie
    pie install --no-build-tools-check thomas-0816/pdo-duckdb-php
    php -m | grep duckdb
    php -r 'print_r(new PDO("duckdb::memory:")->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
EOF
