name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  composer-validate:
    name: "Validate using Composer"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          tools: composer
      - name: Validate
        run: composer validate --strict

  linux_macos:
    name: "Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-14
        php-version:
          - 8.2
          - 8.3
          - 8.4
          - 8.5
        thread-safety:
          - zts
          - nts
    steps:
      - uses: actions/checkout@v6
      - name: Setup PHP ${{ matrix.php-version }} ${{ matrix.thread-safety }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
        env:
          phpts: ${{ matrix.thread-safety }}
          fail-fast: true
      - name: Build & Test
        run: |
          sudo timedatectl set-timezone "Europe/Berlin" || sudo systemsetup -settimezone "Europe/Berlin"
          sudo apt-get -y update
          sudo apt-get -y --no-install-recommends install unzip wget

          case "${{ matrix.os }}" in
            ubuntu-24.04)     libduckdb=libduckdb-linux-amd64.zip ;;
            ubuntu-24.04-arm) libduckdb=libduckdb-linux-arm64.zip ;;
            macos-14)         libduckdb=libduckdb-osx-universal.zip ;;
            *) echo "error ${{ matrix.os }}"; exit 1 ;;
          esac
          wget "https://github.com/duckdb/duckdb/releases/download/v1.5.4/${libduckdb}"
          unzip -o libduckdb-*.zip -d ./
          phpize
          ./configure --with-pdo-duckdb
          make -j$(nproc)
          NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff --show-clean -q" make test
