name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  composer-validate:
    name: "Validate using Composer"
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: '8.5'
          coverage: none
          tools: composer
      - name: Validate
        run: composer validate --strict
  linux_macos:
    name: Linux, MacOS
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - macos-15
        php-version:
          - 8.2
          - 8.3
          - 8.4
          - 8.5
          - 8.6
        thread-safety:
          - zts
          - nts
        variant:
          - plain
          - swoole
        exclude:
          - php-version: 8.6
            variant: swoole
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP ${{ matrix.php-version }} ${{ matrix.thread-safety }} ${{ matrix.variant }}
        uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: ${{ matrix.variant == 'swoole' && 'swoole' || '' }}
        env:
          phpts: ${{ matrix.thread-safety }}
      - name: Build & Test
        env:
          os: ${{ matrix.os }}
          variant: ${{ matrix.variant }}
        run: |
          case "$os" in
            ubuntu-22.04)     libduckdb=static-libs-linux-amd64.zip; sudo timedatectl set-timezone "Europe/Berlin" ;;
            ubuntu-22.04-arm) libduckdb=static-libs-linux-arm64.zip; sudo timedatectl set-timezone "Europe/Berlin" ;;
            macos-15)         libduckdb=static-libs-osx-arm64.zip; sudo systemsetup -settimezone "Europe/Berlin" ;;
            *) echo "error os"; exit 1 ;;
          esac
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/${libduckdb}" -o ${libduckdb}
          unzip -o ${libduckdb} -d ./
          phpize
          ./configure --with-pdo-duckdb
          make
          php -d extension=$(pwd)/modules/pdo_duckdb.so -m | grep duckdb
          NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff --show-clean -q" make test
          php -d extension=$(pwd)/modules/pdo_duckdb.so test.php
          if [ "$variant" = "swoole" ]; then
            php -m
            php -m | grep swoole
            php -d extension=$(pwd)/modules/pdo_duckdb.so test_swoole.php
          fi

  windows:
    name: Windows
    runs-on: ${{ (matrix.php-version == '8.6' && 'windows-2025-vs2026') || 'windows-2022' }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.2
          - 8.3
          - 8.4
          - 8.5
          - 8.6
        ts:
          - nts
          - ts
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Download libduckdb
        shell: bash
        run: |
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-windows-amd64.zip" -o libduckdb-windows-amd64.zip
          unzip -o libduckdb-windows-amd64.zip -d ./
          ls -lisa
          MSYS_NO_PATHCONV=1 tzutil /s "W. Europe Standard Time"
      - name: Build extension
        uses: php/php-windows-builder/extension@29352c0ef9e8ce65264ea9e287881a6f7758a953 # 1.9.0
        with:
          php-version: ${{ matrix.php-version }}
          ts: ${{ matrix.ts }}
          arch: x64
          args: --with-pdo-duckdb
          test-workers: 1
      - name: Setup PHP
        uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: pie
          extensions: swoole-alpha
        env:
          phpts: ${{ matrix.ts }}
      - name: Test extension with Swoole
        if: matrix.php-version != '8.6'
        shell: bash
        run: |
          php -m | grep swoole
          cp ./build/*/x64/Release*/php_pdo_duckdb.dll ./
          php -dextension=$(pwd)/php_pdo_duckdb.dll -m | grep pdo_duckdb
          php -dextension=$(pwd)/php_pdo_duckdb.dll -r 'print_r((new PDO("duckdb::memory:"))->query("SELECT 42 as n")->fetch(PDO::FETCH_ASSOC));'
          php -dextension=$(pwd)/php_pdo_duckdb.dll test_swoole.php

  asan:
    name: ASAN
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build container
        run: |
          docker build --pull --no-cache -f Dockerfile.asan -t pdo_duckdb_asan .
          docker build --pull --no-cache -f Dockerfile.asan_zts -t pdo_duckdb_asan_zts .

  asan-swoole:
    name: ASAN Swoole
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build container
        run: |
          docker build --pull --no-cache -f Dockerfile.asan_swoole -t pdo_duckdb_asan_swoole .
          docker build --pull --no-cache -f Dockerfile.asan_swoole_zts -t pdo_duckdb_asan_swoole_zts .

  valgrind:
    name: Valgrind
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        thread-safety:
          - nts
          - zts
        variant:
          - plain
          - swoole
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: 8.5
          coverage: none
          extensions: ${{ matrix.variant == 'swoole' && 'swoole' || '' }}
        env:
          phpts: ${{ matrix.thread-safety }}
      - name: Build & Test
        run: |
          sudo timedatectl set-timezone "Europe/Berlin"
          sudo apt-get update && sudo apt-get install -y valgrind
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/static-libs-linux-amd64.zip" -o static-libs-linux-amd64.zip
          unzip -o static-libs-linux-amd64.zip -d ./
          phpize
          ./configure --with-pdo-duckdb
          make
          php -m | grep swoole || true
          php -d extension=$(pwd)/modules/pdo_duckdb.so -m | grep duckdb
          NO_INTERACTION=1 TEST_PHP_ARGS="--show-diff --show-clean -q -m -j$(nproc)" make test

  zizmor:
    name: zizmor
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4
        with:
          advanced-security: false
          persona: pedantic

  intree:
    name: InTree
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build PHP with pdo-duckdb-php in-tree
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential autoconf libtool bison re2c pkg-config unzip
          git clone --depth=1 --branch=PHP-8.5 https://github.com/php/php-src.git
          cd php-src/ext
          git clone --depth=1 --branch=main https://github.com/thomas-0816/pdo-duckdb-php.git
          cd pdo-duckdb-php
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/static-libs-linux-amd64.zip" -o static-libs-linux-amd64.zip
          unzip -o static-libs-linux-amd64.zip -d ./
          cd ../../
          ./buildconf --force
          ./configure --disable-all --enable-zts --enable-cli --enable-pcntl --enable-pdo --with-pdo-duckdb
          make -j$(nproc)
          sapi/cli/php -m | grep duckdb
          sapi/cli/php <<'EOF'
              <?php
              if (!extension_loaded("pdo_duckdb")) throw new Exception('Error loading');
              $db = new PDO("duckdb::memory:");
              $db->exec("CREATE TABLE t(i INTEGER, s VARCHAR)");
              $db->exec("INSERT INTO t VALUES (1, 'foo'), (2, 'bar')");
              $t = $db->query("SELECT * FROM t ORDER BY i")->fetchAll(PDO::FETCH_KEY_PAIR);
              if ($t !== ['1' => 'foo', '2' => 'bar']) throw new Exception('Error select');
              echo 'ok', PHP_EOL;
          EOF
          echo 'OK'

  trueasync:
    name: TrueAsync
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build PHP TrueAsync with pdo-duckdb-php in-tree
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential autoconf libtool bison re2c pkg-config unzip libuv1-dev
          git clone --depth=1 --branch=true-async-stable https://github.com/true-async/php-src ./php-src
          git clone --depth=1 --branch=main https://github.com/true-async/php-async ./php-src/ext/async
          git clone --depth=1 --branch=main https://github.com/thomas-0816/pdo-duckdb-php.git ./php-src/ext/pdo-duckdb-php
          cd php-src/ext/pdo-duckdb-php
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/static-libs-linux-amd64.zip" -o static-libs-linux-amd64.zip
          unzip -o static-libs-linux-amd64.zip -d ./
          cd ../../
          ./buildconf --force
          ./configure --disable-all --enable-zts --enable-async --enable-cli --enable-pcntl --enable-pdo --with-pdo-duckdb
          make -j$(nproc)
          sapi/cli/php -m | grep duckdb
          sapi/cli/php <<'EOF'
              <?php
              if (!extension_loaded("pdo_duckdb")) throw new Exception('Error loading');
              $db = new PDO("duckdb::memory:");
              $db->exec("CREATE TABLE t(i INTEGER, s VARCHAR)");
              $db->exec("INSERT INTO t VALUES (1, 'foo'), (2, 'bar')");
              $t = $db->query("SELECT * FROM t ORDER BY i")->fetchAll(PDO::FETCH_KEY_PAIR);
              if ($t !== ['1' => 'foo', '2' => 'bar']) throw new Exception('Error select');
              echo 'ok', PHP_EOL;
          EOF
          sapi/cli/php ext/pdo-duckdb-php/test_trueasync.php
          echo 'OK'

  parallel:
    name: Parallel
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: shivammathur/setup-php@eb7c497e18156a6bbabfef1d3a82760b9eda3962 # 2.40.0
        with:
          php-version: '8.5'
          coverage: none
          extensions: parallel
        env:
          phpts: zts
      - name: Build PHP with pdo-duckdb-php parallel
        run: |
          sudo timedatectl set-timezone "Europe/Berlin"
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/static-libs-linux-amd64.zip" -o static-libs-linux-amd64.zip
          unzip -o static-libs-linux-amd64.zip -d ./
          phpize
          ./configure --with-pdo-duckdb
          make
          php -d extension=$(pwd)/modules/pdo_duckdb.so -m | grep duckdb
          php -d extension=$(pwd)/modules/pdo_duckdb.so test_parallel.php
          echo 'OK'

  frankenphp:
    name: "FrankenPHP"
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build & Test
        run: |
          sudo curl -s https://pkg.henderkes.com/api/packages/85/debian/repository.key -o /etc/apt/keyrings/static-php85.asc
          echo "deb [signed-by=/etc/apt/keyrings/static-php85.asc] https://pkg.henderkes.com/api/packages/85/debian php-zts main" | \
              sudo tee -a /etc/apt/sources.list.d/static-php85.list
          sudo apt-get update
          sudo apt-get install php-zts-cli php-zts-pdo php-zts-devel frankenphp apache2-utils
          sudo timedatectl set-timezone "Europe/Berlin"
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/libduckdb-src.zip" -o libduckdb-src.zip
          unzip -o libduckdb-src.zip duckdb.hpp -d ./
          curl -fsSL "https://github.com/duckdb/duckdb/releases/download/v1.5.6/static-libs-linux-amd64.zip" -o static-libs-linux-amd64.zip
          unzip -o static-libs-linux-amd64.zip -d ./
          phpize-zts
          ./configure --with-pdo-duckdb --with-php-config=php-config-zts
          make
          sudo make install
          sudo sh -c 'echo "extension=pdo_duckdb.so" > /etc/php-zts/conf.d/pdo_duckdb.ini'
          php-zts -m | grep pdo_duckdb
          frankenphp php-server -l 127.0.0.1:8080 -r ./ &
          sleep 3
          curl -IsS http://127.0.0.1:8080/test.php
          ab -n 100 -c 8 -l http://127.0.0.1:8080/test.php 2>&1 | tee /dev/stderr | grep -E "Failed requests:\s+0"
