name: Debug

on:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  linux:
    name: Linux
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-26.04
          - ubuntu-26.04-arm
        php-version:
          - 8.2
          - 8.3
          - 8.4
          - 8.5
          - 8.6
        thread-safety:
          - zts
          - nts
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
        env:
          phpts: ${{ matrix.thread-safety }}
      - name: Debug PHP
        shell: bash
        run: |
          uname -a
          php -v
          php -i
          free
          cat /proc/cpuinfo
